# Generated by Django 3.2.14 on 2023-03-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0003_blogpagerelatedlink_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogPageRelatedLink',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
